name: TransferBox
main: me.modwizcode.plugin.TransferBox.TransferBox
version: 1.0
commands:
  tb:
    description: This is the main command for TransferBox.
    usage: /command select/create <name>/add